version: "3.9"
services:

  frontend:
    image: ghcr.io/flandiayingman/arkwaifu-frontend:latest
    ports:
      - "7081:80"

  service:
    image: ghcr.io/flandiayingman/arkwaifu/service:latest
    ports:
      - "7080:7080"
    volumes:
      - type: bind
        source: ./arkwaifu_resource
        target: /var/arkwaifu_resource
      - type: bind
        source: ./arkwaifu_static
        target: /var/arkwaifu_static
    environment:
      - POSTGRES_DSN
      - RESOURCE_DIR=/var/arkwaifu_resource
      - STATIC_DIR=/var/arkwaifu_static
    extra_hosts:
      - "host.docker.internal:host-gateway"

  updateloop:
    image: ghcr.io/flandiayingman/arkwaifu/updateloop:latest
    volumes:
      - type: bind
        source: ./arkwaifu_resource
        target: /var/arkwaifu_resource
      - type: bind
        source: ./arkwaifu_static
        target: /var/arkwaifu_static
    environment:
      - POSTGRES_DSN
      - ARKRES_CHAT_MASK
      - RESOURCE_DIR=/var/arkwaifu_resource
      - STATIC_DIR=/var/arkwaifu_static
      - FORCE_UPDATE=$FORCE_UPDATE
      - FORCE_SUBMIT=$FORCE_SUBMIT
    extra_hosts:
      - "host.docker.internal:host-gateway"

