name: "Docker Image CI: service"

on:
  push:
    branches: [ master ]
    tags:
      - "v**"
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: "ghcr.io"
          # Username used to log against the Docker registry
          username: ${{ github.actor }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          # List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)
          # cache-from: # optional
          # List of cache export destinations for buildx (e.g., user/app:cache, type=local,dest=path/to/dir)
          # cache-to: # optional
          # Path to the Dockerfile
          file: "build/service.Dockerfile"
          # Push is a shorthand for --output=type=registry
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          # List of tags
          tags: |
            ghcr.io/flandiayingman/arkwaifu/service:latest
            ghcr.io/flandiayingman/arkwaifu/service:${{ github.ref_name }}
